[package]
name = "hsmpki"
version = "0.1.0"
edition = "2024"

[dependencies]
cryptoki = "0.10.0"
rand = "0.8"
rcgen = "0.14.5"
rsa = "0.9.8"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"]}
uuid = { version = "1.18.1", features = ["v4"]}
x509-cert = "0.2.5"
